project_id = "gewoavxkobecdjsmozhn"
[api]
enabled = true
schemas = ["public", "graphql_public"]
[auth]
enabled = true
site_url = "https://aldaconnect.vercel.app"
additional_redirect_urls = ["https://aldaconnect.vercel.app/auth/callback", "http://127.0.0.1:4310/auth/callback"]
minimum_password_length = 12

[auth.email]
enable_confirmations = true
max_frequency = "1m0s"
otp_length = 8

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[db.pooler]
default_pool_size = 15
max_client_conn = 200

[storage.analytics]
enabled = true
max_namespaces = 10

[storage.image_transformation]
enabled = true
